-- members
INSERT INTO members (EMAIL , GENDER , NAME , NICKNAME , PASSWORD , PHONE) VALUES ('test1@naver.com','male','이종화1','sudburning1','tt02204365??','01066974365')
INSERT INTO members (EMAIL , GENDER , NAME , NICKNAME , PASSWORD , PHONE) VALUES ('test2@naver.com','male','이종화2','sudburning2','tt02204365??','01066974365')
INSERT INTO members (EMAIL , GENDER , NAME , NICKNAME , PASSWORD , PHONE) VALUES ('test3@naver.com','male','이종화3','sudburning3','tt02204365??','01066974365')
INSERT INTO members (EMAIL , GENDER , NAME , NICKNAME , PASSWORD , PHONE) VALUES ('test4@naver.com','male','이종화4','sudburning4','tt02204365??','01066974365')


-- orders
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212a' , 1 , '람보르기니' , CURRENT_TIMESTAMP)
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212b' , 1 , '포르쉐' , CURRENT_TIMESTAMP)
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212c' , 1 , '벤츠' , CURRENT_TIMESTAMP)
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212d' , 2 , 'BMW' , CURRENT_TIMESTAMP)
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212e' , 2 , '폭스바겐' , CURRENT_TIMESTAMP)
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212f' , 3 , '테슬라' , CURRENT_TIMESTAMP)
INSERT INTO orders (ORDERSERIAL , MEMBERID , PRODUCTNAME , PAYMENTDATE) VALUES ('20220212g' , 3 , '아우디' , CURRENT_TIMESTAMP)